on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: ${{ (endsWith(github.ref, '_dev') && 'dev') || (endsWith(github.ref, '_qa') && 'qa') || inputs.environment || '' }}

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.TEST_SECRET }}" > .env
      - run: echo "${{ github.ref	}}
      - uses: actions/upload-artifact@v4
        with:
          name: env
          path: .env
