on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.TEST_SECRET }}" > .env
      - run: wc -l .env
      - run: ls
      - uses: actions/upload-artifact@v4
        with:
          name: env
          path: .env
