on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.TEST_SECRET }}" > .env
      - run: wc -l .env
      - run: ls
      - run: pwd
      - run: echo "${{ github.workspace }}"
      - run: '[ "$(cat .env)" = "${{ secrets.TEST_SECRET }}" ] && echo "Verified" || echo "Verification failed"'      
      - uses: actions/upload-artifact@v4
        with:
          name: env
          path: .env
